"use client";
// Rumbo UI: cabecera personal, tripulación por tramo y biblioteca editable.

import { useEffect, useMemo, useRef, useState } from "react";

type CrewMember={id?:string;role:string;name:string};
type Leg = { flight: string; from: string; to: string; departL: string; arriveL: string; departZ: string; arriveZ: string; block: string; crew?:CrewMember[] };
type Duty = { date: string; type: "flight"|"standby"|"nda"|"off"|"sim"|"training"|"leave"; title: string; report?: string; reportZ?: string; reportPlace?: string; end?: string; endZ?: string; total?: string; note?: string; legs?: Leg[]; owner?:string; crew?:CrewMember[] };
type SavedRoster={id:string;name:string;importedAt:string;from:string;to:string;count:number};

const duties: Duty[] = [
  {date:"2025-06-27",type:"sim",title:"REC SIM",report:"03:15",reportZ:"06:15",reportPlace:"Cefepra AEP",end:"08:15",endZ:"11:15",total:"00:00",note:"Trainee - REC SIM, Cefepra AEP"},
  {date:"2025-06-28",type:"sim",title:"Eficiencia",report:"03:15",reportZ:"06:15",reportPlace:"Cefepra AEP",end:"08:15",endZ:"11:15",total:"00:00",note:"Trainee - Eficiencia, Cefepra AEP"},
  {date:"2025-06-29",type:"nda",title:"NDA",report:"00:00",reportZ:"03:00",end:"23:59",endZ:"02:59"},
  {date:"2025-06-30",type:"nda",title:"NDA",report:"00:00",reportZ:"03:00",end:"23:59",endZ:"02:59"},
  ...Array.from({length:15},(_,i)=>({date:`2025-07-${String(i+1).padStart(2,"0")}`,type:"leave" as const,title:"VAC15 AC",report:"00:00",reportZ:"03:00",end:"23:59",endZ:"02:59",note:"Licencia anual"})),
  ...[16,17,18].map(d=>({date:`2025-07-${d}`,type:"off" as const,title:"R-OFF",report:"00:00",reportZ:"03:00",end:"23:59",endZ:"02:59"})),
  {date:"2025-07-19",type:"flight",title:"4 vuelos",report:"06:00",reportZ:"09:00",reportPlace:"EZE",end:"16:41",endZ:"19:41",total:"07:16",note:"OP - (RS)",legs:[
    {flight:"FO5300",from:"EZE",to:"NQN",departL:"06:54",arriveL:"08:43",departZ:"09:54",arriveZ:"11:43",block:"01:49"},
    {flight:"FO5301",from:"NQN",to:"AEP",departL:"09:17",arriveL:"11:11",departZ:"12:17",arriveZ:"14:11",block:"01:54"},
    {flight:"FO5230",from:"AEP",to:"SDE",departL:"12:38",arriveL:"14:22",departZ:"15:38",arriveZ:"17:22",block:"01:44"},
    {flight:"FO5231",from:"SDE",to:"AEP",departL:"14:52",arriveL:"16:41",departZ:"17:52",arriveZ:"19:41",block:"01:49"}]},
  {date:"2025-07-20",type:"flight",title:"2 vuelos",report:"18:30",reportZ:"21:30",reportPlace:"AEP",end:"01:05",endZ:"04:05",total:"04:18",note:"Finaliza el 21 de julio · OP - (RS)",legs:[
    {flight:"FO5250",from:"AEP",to:"BRC",departL:"20:10",arriveL:"22:34",departZ:"23:10",arriveZ:"01:34",block:"02:24"},
    {flight:"FO5251",from:"BRC",to:"EZE",departL:"23:11",arriveL:"01:05",departZ:"02:11",arriveZ:"04:05",block:"01:54"}]},
  {date:"2025-07-22",type:"flight",title:"2 vuelos",report:"05:30",reportZ:"08:30",reportPlace:"EZE",end:"11:41",endZ:"14:41",total:"04:39",note:"OP - (RS)",legs:[
    {flight:"FO5240",from:"EZE",to:"BRC",departL:"06:28",arriveL:"09:06",departZ:"09:28",arriveZ:"12:06",block:"02:38"},{flight:"FO5241",from:"BRC",to:"AEP",departL:"09:40",arriveL:"11:41",departZ:"12:40",arriveZ:"14:41",block:"02:01"}]},
  {date:"2025-07-23",type:"nda",title:"NDA",report:"00:00",reportZ:"03:00",end:"23:59",endZ:"02:59"},
  {date:"2025-07-24",type:"flight",title:"2 vuelos",report:"08:50",reportZ:"11:50",reportPlace:"AEP",end:"14:03",endZ:"17:03",total:"03:33",note:"OP - (RS)",legs:[{flight:"FO5210",from:"AEP",to:"TUC",departL:"09:58",arriveL:"11:46",departZ:"12:58",arriveZ:"14:46",block:"01:48"},{flight:"FO5211",from:"TUC",to:"AEP",departL:"12:18",arriveL:"14:03",departZ:"15:18",arriveZ:"17:03",block:"01:45"}]},
  {date:"2025-07-25",type:"flight",title:"2 vuelos",report:"16:00",reportZ:"19:00",reportPlace:"AEP",end:"22:22",endZ:"01:22",total:"04:15",note:"OP - (RS)",legs:[{flight:"FO5180",from:"AEP",to:"JUJ",departL:"17:13",arriveL:"19:28",departZ:"20:13",arriveZ:"22:28",block:"02:15"},{flight:"FO5181",from:"JUJ",to:"EZE",departL:"20:22",arriveL:"22:22",departZ:"23:22",arriveZ:"01:22",block:"02:00"}]},
  {date:"2025-07-26",type:"flight",title:"4 vuelos",report:"12:05",reportZ:"15:05",reportPlace:"AEP",end:"22:52",endZ:"01:52",total:"07:14",note:"OP - (RS)",legs:[{flight:"FO5150",from:"AEP",to:"CNQ",departL:"13:10",arriveL:"14:43",departZ:"16:10",arriveZ:"17:43",block:"01:33"},{flight:"FO5151",from:"CNQ",to:"AEP",departL:"15:09",arriveL:"16:36",departZ:"18:09",arriveZ:"19:36",block:"01:27"},{flight:"FO5162",from:"AEP",to:"SLA",departL:"18:04",arriveL:"20:21",departZ:"21:04",arriveZ:"23:21",block:"02:17"},{flight:"FO5163",from:"SLA",to:"EZE",departL:"20:55",arriveL:"22:52",departZ:"23:55",arriveZ:"01:52",block:"01:57"}]},
  {date:"2025-07-27",type:"nda",title:"NDA",report:"00:00",reportZ:"03:00",end:"23:59",endZ:"02:59"},
  {date:"2025-07-28",type:"nda",title:"NDA",report:"00:00",reportZ:"03:00",end:"23:59",endZ:"02:59"},
  {date:"2025-07-29",type:"flight",title:"4 vuelos",report:"05:30",reportZ:"08:30",reportPlace:"AEP",end:"14:14",endZ:"17:14",total:"05:43",note:"OP - (RS)",legs:[{flight:"FO5000",from:"AEP",to:"COR",departL:"06:25",arriveL:"07:51",departZ:"09:25",arriveZ:"10:51",block:"01:26"},{flight:"FO5001",from:"COR",to:"AEP",departL:"08:29",arriveL:"09:40",departZ:"11:29",arriveZ:"12:40",block:"01:11"},{flight:"FO5150",from:"AEP",to:"CNQ",departL:"10:35",arriveL:"12:03",departZ:"13:35",arriveZ:"15:03",block:"01:28"},{flight:"FO5151",from:"CNQ",to:"AEP",departL:"12:36",arriveL:"14:14",departZ:"15:36",arriveZ:"17:14",block:"01:38"}]},
  {date:"2025-07-30",type:"nda",title:"NDA",report:"00:00",reportZ:"03:00",end:"23:59",endZ:"02:59"},
  {date:"2025-07-31",type:"flight",title:"2 vuelos",report:"07:00",reportZ:"10:00",reportPlace:"AEP",end:"12:53",endZ:"15:53",total:"04:11",note:"OP - (RS)",legs:[{flight:"FO5160",from:"AEP",to:"SLA",departL:"08:09",arriveL:"10:22",departZ:"11:09",arriveZ:"13:22",block:"02:13"},{flight:"FO5161",from:"SLA",to:"AEP",departL:"10:55",arriveL:"12:53",departZ:"13:55",arriveZ:"15:53",block:"01:58"}]},
];

const icon: Record<Duty["type"],string>={flight:"",standby:"⌂",nda:"⌂",off:"❄",sim:"",training:"▣",leave:"☀"};
function DutyIcon({type}:{type:Duty["type"]}){
  if(type==="flight")return <svg className="duty-svg plane-svg" viewBox="0 0 48 32" aria-hidden="true"><path d="M3 22.8 19.2 18l7.5-12.2c.7-1.1 1.9-1.8 3.2-1.8h2l-3.7 12.1 10.7-3.2c2.8-.8 5.8.4 7.2 3l.7 1.5-17.5 8.1-8.1 1.9-8.7-1.8-5.8 1.7-2.1-1.1L3 22.8Zm17.1-4.5-7.3-6.1 3.3-1 10.2 5.3-6.2 1.8Z"/></svg>;
  if(type==="sim")return <svg className="duty-svg sim-svg" viewBox="0 0 32 32" aria-hidden="true"><path d="M5 5.5h22v14H5zM8 8.5h16v7.5H8zM3.5 19.5h25l-2.4 6H5.9l-2.4-6ZM11 25.5v2h10v-2"/><path d="M9 19.5v3m14-3v3M13 19.5l1.5 3m4-3-1 3"/></svg>;
  if(type==="standby"||type==="nda"||type==="leave")return <svg className="duty-svg house-svg" viewBox="0 0 32 32" aria-hidden="true"><path d="M4.5 15.2 16 5l11.5 10.2v12.3H4.5V15.2Z"/><path d="M12.2 27.5v-8.3h7.6v8.3M22.5 6.5v4.3"/></svg>;
  if(type==="off")return <svg className="duty-svg house-svg snow-house-svg" viewBox="0 0 32 32" aria-hidden="true"><path d="M4.5 14.2 16 4l11.5 10.2v12.3H4.5V14.2Z"/><path d="M12.2 26.5v-8.3h7.6v8.3M22.5 5.5v4.3M16 10.5v6m-3-3h6m-5.1-2.1 4.2 4.2m0-4.2-4.2 4.2"/></svg>;
  return <span aria-hidden="true">{icon[type]}</span>;
}
const weekdays=["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"];
const months=["enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre"];
const pad=(n:number)=>String(n).padStart(2,"0");
const key=(y:number,m:number,d:number)=>`${y}-${pad(m+1)}-${pad(d)}`;
type ClockMode="local"|"zulu";
const shiftZulu=(value:string|undefined,offset:number)=>{if(!value)return "—";const [h,m]=value.split(":").map(Number);return `${pad((h+offset+24)%24)}:${pad(m)}`};
const zoneLabel=(offset:number)=>offset===0?"UTC / Zulu":`UTC ${offset>0?"+":""}${offset}`;
const isAllDayDuty=(duty:Duty)=>{
  if(!duty.report&&!duty.reportZ&&!duty.end&&!duty.endZ)return true;
  if(!["leave","nda","off"].includes(duty.type))return false;
  return duty.report==="00:00"&&duty.end==="23:59";
};

function DayDetail({duty,onClose,offset,clock}:{duty:Duty,onClose:()=>void,offset:number,clock:ClockMode}){
  const day=new Date(duty.date+"T12:00:00");
  const local=(z:string|undefined)=>shiftZulu(z,offset);
  const [openLeg,setOpenLeg]=useState<number|null>(null);
  const allDay=isAllDayDuty(duty);
  return <div className="scrim" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="detail" role="dialog" aria-modal="true" aria-label={`Detalle del ${day.getDate()} de ${months[day.getMonth()]}`}>
    <button className="close" onClick={onClose} aria-label="Cerrar detalle">×</button>
    <p className="eyebrow">{day.toLocaleDateString("es-AR",{weekday:"long",day:"numeric",month:"long"})}</p>
    <div className="detail-title"><span className={`big-icon ${duty.type}`}><DutyIcon type={duty.type}/></span><div><h2>{duty.type==="flight"?"Jornada de vuelo":duty.title}</h2><p>{allDay?"Todo el día":duty.type==="flight"?(duty.legs?.length?`${duty.legs.length} tramo${duty.legs.length===1?"":"s"}${duty.total?` · ${duty.total} de vuelo`:""}`:"Datos de tramo no disponibles en este PDF"):duty.note||"Actividad programada"}</p></div></div>
    {!allDay&&<><div className="time-head"><span>{clock==="local"?`TU HORA · ${zoneLabel(offset)}`:"HORA ZULU"}</span><span>{clock==="local"?"ZULU":"TU HORA"}</span></div>
    <div className="timeline">
      <div className="point"><i/><div><small>PRESENTACIÓN {duty.reportPlace&&`· ${duty.reportPlace}`}</small><strong>{clock==="local"?local(duty.reportZ):duty.reportZ}</strong></div><b>{clock==="local"?`${duty.reportZ||"—"} Z`:local(duty.reportZ)}</b></div>
      {duty.legs?.map((leg,i)=><button type="button" className={`point leg ${openLeg===i?"expanded":""}`} key={`${leg.flight}-${i}`} onClick={()=>setOpenLeg(openLeg===i?null:i)}><i/><div><small>TRAMO {i+1} · {leg.flight}</small><strong>{leg.from} <em>→</em> {leg.to}</strong><p>{clock==="local"?`${local(leg.departZ)} — ${local(leg.arriveZ)}`:`${leg.departZ} — ${leg.arriveZ} Z`} · Bloque {leg.block}</p>{openLeg===i&&leg.crew?.length&&<div className="leg-crew"><span>TRIPULACIÓN DEL TRAMO</span>{leg.crew.map((member,j)=><small key={`${member.id}-${member.role}-${j}`}><b>{member.role}</b> {member.name}{member.id?` · Legajo ${member.id}`:""}</small>)}</div>}</div><b>{clock==="local"?`${leg.departZ} — ${leg.arriveZ} Z`:`${local(leg.departZ)} — ${local(leg.arriveZ)}`}</b></button>)}
      <div className="point end"><i/><div><small>FINALIZACIÓN</small><strong>{clock==="local"?local(duty.endZ):duty.endZ}</strong></div><b>{clock==="local"?`${duty.endZ||"—"} Z`:local(duty.endZ)}</b></div>
    </div></>}
    {duty.note&&<div className="note"><span>OBSERVACIONES</span><p>{duty.note}</p></div>}
  </section></div>
}

function SettingsModal({clock,offset,onSave,onClose}:{clock:ClockMode,offset:number,onSave:(c:ClockMode,o:number)=>void,onClose:()=>void}){
  const [draftClock,setDraftClock]=useState(clock);const [draftOffset,setDraftOffset]=useState(offset);
  return <div className="scrim settings-scrim" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="settings-card" role="dialog" aria-modal="true" aria-label="Configuración de horario"><button className="close" onClick={onClose}>×</button><p className="eyebrow">PREFERENCIAS</p><h2>Cómo querés ver la hora</h2><p className="settings-intro">La elección se guarda en este dispositivo y se aplica al calendario, la agenda y los detalles.</p><div className="clock-options"><button className={draftClock==="local"?"selected":""} onClick={()=>setDraftClock("local")}><span>◷</span><div><b>Hora local</b><small>Convertida al huso que elijas</small></div><i>{draftClock==="local"?"✓":""}</i></button><button className={draftClock==="zulu"?"selected":""} onClick={()=>setDraftClock("zulu")}><span>Z</span><div><b>Hora Zulu</b><small>UTC, estándar aeronáutico</small></div><i>{draftClock==="zulu"?"✓":""}</i></button></div><label className="offset-field"><span>DESFASE DE TU HORA LOCAL</span><select value={draftOffset} onChange={e=>setDraftOffset(Number(e.target.value))}>{Array.from({length:27},(_,i)=>i-12).map(o=><option key={o} value={o}>{zoneLabel(o)}{o===-3?" · Buenos Aires":""}</option>)}</select><small>Ejemplo: Buenos Aires es UTC -3.</small></label><button className="save-settings" onClick={()=>{onSave(draftClock,draftOffset);onClose()}}>Guardar configuración</button></section></div>
}

const pdfMonths:Record<string,number>={Jan:0,Feb:1,Mar:2,Apr:3,May:4,Jun:5,Jul:6,Aug:7,Sep:8,Oct:9,Nov:10,Dec:11};
async function parseRosterPdf(buf:ArrayBuffer){
  const pdfUrl="https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.624/build/pdf.min.mjs";const workerUrl="https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.624/build/pdf.worker.min.mjs";
  const pdfjs:any=await import(/* @vite-ignore */ pdfUrl);pdfjs.GlobalWorkerOptions.workerSrc=workerUrl;const pdf=await pdfjs.getDocument({data:new Uint8Array(buf)}).promise;let text="";
  for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p);const content=await page.getTextContent();text+="\n"+content.items.map((item:any)=>item.str).join(" ")}
  if(!/CREW\s+DAILY\s+ROSTER/i.test(text))throw new Error("Este PDF no parece ser un Crew Daily Roster de ARMS.");
  const matches=[...text.matchAll(/\b(\d{1,2})-(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)-(\d{4})\b/g)];const seen=new Set<string>();const parsed:Duty[]=[];
  matches.forEach((match,i)=>{const date=`${match[3]}-${pad(pdfMonths[match[2]]+1)}-${pad(Number(match[1]))}`;if(seen.has(date))return;seen.add(date);const start=Math.max(0,(match.index||0)-550),end=Math.min(text.length,(matches[i+1]?.index||match.index!+800)+150);const window=text.slice(start,end),dutyLine=text.slice(match.index||0,Math.min(text.length,(match.index||0)+120));let type:Duty["type"]="flight",title="Jornada de vuelo";if(/R-OFF|\bOFF\b/i.test(dutyLine)){type="off";title=/R-OFF/i.test(dutyLine)?"R-OFF":"OFF"}else if(/\bNDA\b/i.test(dutyLine)){type="nda";title="NDA"}else if(/STBY|STANDBY|GUARDIA/i.test(dutyLine)){type="standby";title="STBY"}else if(/\bSIM\b/i.test(dutyLine)){type="sim";title="Simulador"}else if(/GROUND|TRAINING|CAPACIT/i.test(dutyLine)){type="training";title="Capacitación"}else if(/LEAVE|VAC\d*/i.test(dutyLine)){type="leave";title="Licencia"}
    const local=[...window.matchAll(/(\d{2}:\d{2})\s*\(L\)/g)].map(x=>x[1]);const zulu=[...window.matchAll(/(\d{2}:\d{2})\s*\(Z\)/g)].map(x=>x[1]);const flights=[...new Set([...window.matchAll(/\b([A-Z]{2}\d{3,4}[A-Z]?)\b/g)].map(x=>x[1]))];const places=[...window.matchAll(/\b([A-Z]{3})\s*[-–]\s*([A-Z]{3})\b/g)];if(type==="flight"&&flights.length)title=`${flights.length} vuelo${flights.length===1?"":"s"}`;
    const legCount=Math.min(flights.length,places.length);const legs:Leg[]=Array.from({length:legCount},(_,n)=>({flight:flights[n],from:places[n][1],to:places[n][2],departL:local[1+n*2]||"—",arriveL:local[2+n*2]||"—",departZ:zulu[1+n*2]||"—",arriveZ:zulu[2+n*2]||"—",block:"—"}));if(type==="flight"&&legs.length)title=`${legs.length} vuelo${legs.length===1?"":"s"}`;
    parsed.push({date,type,title,report:local[0],reportZ:zulu[0],reportPlace:legs[0]?.from,end:local.at(-1),endZ:zulu.at(-1),note:window.match(/OP\s*-\s*\([^)]+\)/i)?.[0]||"Importado desde ARMS",legs:type==="flight"?legs:undefined})});
  if(!parsed.length)throw new Error("No encontramos fechas de servicio en el PDF.");return parsed.sort((a,b)=>a.date.localeCompare(b.date));
}

async function parseRosterPdfByRows(buf:ArrayBuffer){
  const pdfUrl="https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.624/build/pdf.min.mjs",workerUrl="https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.624/build/pdf.worker.min.mjs";const pdfjs:any=await import(/* @vite-ignore */ pdfUrl);pdfjs.GlobalWorkerOptions.workerSrc=workerUrl;const pdf=await pdfjs.getDocument({data:new Uint8Array(buf)}).promise;const parsed:Duty[]=[];let recognized=false;
  for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),content=await page.getTextContent(),raw=content.items.filter((x:any)=>x.str?.trim()).map((x:any)=>({text:x.str.trim(),x:x.transform[4],y:x.transform[5]}));if(raw.some((x:any)=>/CREW DAILY ROSTER/i.test(x.text)))recognized=true;const rows:{y:number,parts:{text:string,x:number}[]}[]=[];raw.forEach((item:any)=>{let row=rows.find(r=>Math.abs(r.y-item.y)<2);if(!row){row={y:item.y,parts:[]};rows.push(row)}row.parts.push({text:item.text,x:item.x})});rows.forEach(r=>r.parts.sort((a,b)=>a.x-b.x));const lines=rows.map(r=>({y:r.y,text:r.parts.map(x=>x.text).join(" ")})).sort((a,b)=>b.y-a.y);const anchors=lines.map((r,i)=>{const m=r.text.match(/^\s*\d+\s+(\d{1,2})-(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)-(\d{4})\b(.*)$/);return m?{i,y:r.y,m}:null}).filter(Boolean) as {i:number,y:number,m:RegExpMatchArray}[];
    anchors.forEach((a,idx)=>{const upper=idx?((anchors[idx-1].y+a.y)/2):Infinity,lower=idx<anchors.length-1?((a.y+anchors[idx+1].y)/2):-Infinity,bucket=lines.filter(r=>r.y<=upper&&r.y>lower).map(r=>r.text).join(" "),dutyLine=a.m[4]||"";const date=`${a.m[3]}-${pad(pdfMonths[a.m[2]]+1)}-${pad(Number(a.m[1]))}`;let type:Duty["type"]="flight",title="Jornada de vuelo";if(/R-OFF|\bOFF\b/i.test(bucket)){type="off";title=/R-OFF/i.test(bucket)?"R-OFF":"OFF"}else if(/\bNDA\b/i.test(bucket)){type="nda";title="NDA"}else if(/STBY|STANDBY|GUARDIA/i.test(bucket)){type="standby";title="STBY"}else if(/\bSIM\b/i.test(bucket)){type="sim";title=dutyLine.replace(/^\s*SIM\s*-?\s*/i,"").trim()||"Simulador"}else if(/GROUND|TRAINING|CAPACIT/i.test(bucket)){type="training";title=dutyLine.trim()}else if(/LEAVE|VAC\d*/i.test(bucket)){type="leave";title=dutyLine.trim()||"Licencia"}const flights=[...new Set([...bucket.matchAll(/\b([A-Z]{2}\d{3,4}[A-Z]?)\b/g)].map(x=>x[1]))],routes=[...bucket.matchAll(/\b([A-Z]{3})\s*[-–]\s*([A-Z]{3})\b/g)],local=[...bucket.matchAll(/(\d{2}:\d{2})\s*\(L\)/g)].map(x=>x[1]),zulu=[...bucket.matchAll(/(\d{2}:\d{2})\s*\(Z\)/g)].map(x=>x[1]),count=Math.min(flights.length,routes.length),legs:Leg[]=Array.from({length:count},(_,n)=>({flight:flights[n],from:routes[n][1],to:routes[n][2],departL:local[1+n*2]||"—",arriveL:local[2+n*2]||"—",departZ:zulu[1+n*2]||"—",arriveZ:zulu[2+n*2]||"—",block:"—"}));if(type==="flight")title=legs.length?`${legs.length} vuelo${legs.length===1?"":"s"}`:"Jornada de vuelo";parsed.push({date,type,title,report:local[0],reportZ:zulu[0],reportPlace:legs[0]?.from,end:local.at(-1),endZ:zulu.at(-1),note:bucket.match(/OP\s*-\s*\([^)]+\)/i)?.[0]||dutyLine.trim()||undefined,legs:type==="flight"?legs:undefined})})}
  if(!recognized)throw new Error("Este PDF no parece ser un Crew Daily Roster de ARMS.");if(!parsed.length)throw new Error("No encontramos fechas de servicio en el PDF.");return parsed.sort((a,b)=>a.date.localeCompare(b.date));
}

async function parseRosterPdfStrict(buf:ArrayBuffer){
  const pdfUrl="https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.624/build/pdf.min.mjs",workerUrl="https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.624/build/pdf.worker.min.mjs";const pdfjs:any=await import(/* @vite-ignore */ pdfUrl);pdfjs.GlobalWorkerOptions.workerSrc=workerUrl;const pdf=await pdfjs.getDocument({data:new Uint8Array(buf)}).promise;const dutiesByDate=new Map<string,Duty>();let recognized=false,owner="";let carryLines:any[]=[];
  for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),content=await page.getTextContent(),raw=content.items.filter((v:any)=>v.str?.trim()).map((v:any)=>({text:v.str.trim(),x:v.transform[4],y:v.transform[5]}));const pageText=raw.map((v:any)=>v.text).join(" ");if(/CREW DAILY ROSTER/i.test(pageText))recognized=true;if(!owner){const om=pageText.match(/CREW DAILY ROSTER.{0,160}?([A-ZÁÉÍÓÚÑ]{3,}(?:\s+[A-ZÁÉÍÓÚÑ]{3,}){1,3})/);if(om&&!/CREW|DAILY|ROSTER/.test(om[1]))owner=om[1]}
    const rows:{y:number,parts:{text:string,x:number}[]}[]=[];raw.forEach((v:any)=>{let row=rows.find(r=>Math.abs(r.y-v.y)<2);if(!row){row={y:v.y,parts:[]};rows.push(row)}row.parts.push({text:v.text,x:v.x})});const lines=rows.map(r=>({y:r.y,parts:r.parts.sort((a,b)=>a.x-b.x),text:r.parts.map(v=>v.text).join(" ")})).sort((a,b)=>b.y-a.y);const dateRe=/^\s*\d+\s+(\d{1,2})-(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)-(\d{4})\b(.*)$/;const anchors=lines.map((r,i)=>{const m=r.text.match(dateRe);return m?{i,y:r.y,m,date:`${m[3]}-${pad(pdfMonths[m[2]]+1)}-${pad(Number(m[1]))}`}:null}).filter(Boolean) as {i:number,y:number,m:RegExpMatchArray,date:string}[];
    if(!owner){const header=lines.find(r=>/CREW DAILY ROSTER/i.test(r.text));const om=header?.text.match(/CREW DAILY ROSTER\s+([A-ZÁÉÍÓÚÑ]{3,}(?:\s+[A-ZÁÉÍÓÚÑ]{3,}){1,3})/);if(om&&!/CREW|DAILY|ROSTER/.test(om[1]))owner=om[1]}
    anchors.forEach((a,idx)=>{
      const upper=idx?(anchors[idx-1].y+a.y)/2:Infinity,lower=idx<anchors.length-1?(a.y+anchors[idx+1].y)/2:-Infinity;
      const text=lines.filter(r=>r.y<=upper&&r.y>lower).map(r=>r.text).join(" ");
      // ARMS imprime el código de actividad en una columna propia (x 92-148).
      // La clasificación usa solamente esa celda de la misma fila de fecha.
      const activityCode=lines[a.i].parts.filter(v=>v.x>=92&&v.x<148).map(v=>v.text).join(" ").trim();
      let type:Duty["type"]="flight",title="Jornada de vuelo";
      if(/^R-OFF\b/i.test(activityCode)){type="off";title="R-OFF"}
      else if(/^OFF\b/i.test(activityCode)){type="off";title="OFF"}
      else if(/^NDA\b/i.test(activityCode)){type="nda";title="NDA"}
      else if(/^(?:STBY|STANDBY|STB)\b/i.test(activityCode)){type="standby";title="STBY"}
      else if(/^SIM\b/i.test(activityCode)){type="sim";title=activityCode||"Simulador"}
      else if(/^(?:GROUND|TRAINING|CAPACIT)/i.test(activityCode)){type="training";title=activityCode}
      else if(/^(?:LVE|LEAVE|VAC\d*|Suspensión)/i.test(activityCode)){type="leave";title=activityCode||"Licencia"}
      const local=[...text.matchAll(/(\d{2}:\d{2})\s*\(L\)/g)].map(x=>x[1]),zulu=[...text.matchAll(/(\d{2}:\d{2})\s*\(Z\)/g)].map(x=>x[1]);
      dutiesByDate.set(a.date,{date:a.date,type,title,report:local[0],reportZ:zulu[0],end:local.at(-1),endZ:zulu.at(-1),note:text.match(/Vuelo a definir[^\d]*/i)?.[0]?.trim(),owner})
    });
    const flowLines=carryLines.length?[...carryLines,...lines]:lines;carryLines=[];const flowAnchors=flowLines.map((r,i)=>{const m=r.text.match(dateRe);return m?{i,y:r.y,m,date:`${m[3]}-${pad(pdfMonths[m[2]]+1)}-${pad(Number(m[1]))}`}:null}).filter(Boolean) as {i:number,y:number,m:RegExpMatchArray,date:string}[];
    const allFlightRows=flowLines.map((r,i)=>/\b[A-Z]{2}\d{3,4}[A-Z]?\b/.test(r.text)?i:-1).filter(i=>i>=0);const crewForRow=(rowIndex:number)=>{const pos=allFlightRows.indexOf(rowIndex),lower=pos>=0&&pos<allFlightRows.length-1?allFlightRows[pos+1]:flowLines.length,right=flowLines.slice(rowIndex,lower).flatMap(r=>r.parts.filter(v=>v.x>=470).map(v=>v.text)).join(" "),members:CrewMember[]=[];for(const m of right.matchAll(/\((\d+)\)\s+(.+?)\s+\((CC|PU|LS|CAPT|PIC|COP|FO|SCCM|CCM|TCP)\)/gi)){members.push({id:m[1],name:m[2].trim(),role:m[3].toUpperCase()})}return members};
    const starts=flowLines.map((r,i)=>(r.text.match(/\d{2}:\d{2}\(Z\)/g)||[]).length>=3?i:-1).filter(i=>i>=0);starts.forEach((start,si)=>{const segment=flowLines.slice(start,starts[si+1]??flowLines.length),text=segment.map(r=>r.text).join(" "),anchor=flowAnchors.find(a=>a.i>=start&&a.i<(starts[si+1]??flowLines.length));if(!anchor)return;const flights=[...new Set([...text.matchAll(/\b([A-Z]{2}\d{3,4}[A-Z]?)\b/g)].map(x=>x[1]))],routes=[...text.matchAll(/\b([A-Z]{3})\s*[-–]\s*([A-Z]{3})\b/g)];if(!flights.length||flights.length!==routes.length)return;const zTimes=[...text.matchAll(/(\d{2}:\d{2})\(Z\)/g)].map(v=>v[1]),lTimes=[...text.matchAll(/(\d{2}:\d{2})\(L\)/g)].map(v=>v[1]),reportZ=zTimes[0],report=lTimes[0],depArrZ=zTimes.slice(1),depArrL=lTimes.slice(1),bareTimes=segment.flatMap(r=>r.parts).filter(v=>v.x>290&&v.x<470&&/^\d{2}:\d{2}$/.test(v.text)).map(v=>v.text),blocks=bareTimes.slice(0,flights.length),total=bareTimes.length>flights.length?bareTimes.at(-1):undefined,legs=flights.map((flight,i)=>({flight,from:routes[i][1],to:routes[i][2],departL:depArrL[i*2]||"—",arriveL:depArrL[i*2+1]||"—",departZ:depArrZ[i*2]||"—",arriveZ:depArrZ[i*2+1]||"—",block:blocks[i]||"—",crew:crewForRow(start+segment.findIndex(r=>new RegExp(`\\b${flight}\\b`).test(r.text)))}));const crew=[...new Map(legs.flatMap(l=>l.crew||[]).map(c=>[`${c.id}-${c.role}-${c.name}`,c])).values()];dutiesByDate.set(anchor.date,{date:anchor.date,type:"flight",title:`${legs.length} vuelo${legs.length===1?"":"s"}`,report,reportZ,reportPlace:legs[0].from,end:legs.at(-1)?.arriveL,endZ:legs.at(-1)?.arriveZ,total,note:text.match(/OP\s*-\s*\([^)]+\)/i)?.[0],legs,owner,crew})});if(starts.length)carryLines=flowLines.slice(starts.at(-1)!)}
  if(!recognized)throw new Error("Este PDF no parece ser un Crew Daily Roster de ARMS.");const result=[...dutiesByDate.values()].sort((a,b)=>a.date.localeCompare(b.date));if(!result.length)throw new Error("No encontramos jornadas estructuradas en el PDF.");return result;
}

const rosterDb=()=>new Promise<IDBDatabase>((resolve,reject)=>{const req=indexedDB.open("rumbo-rosters",1);req.onupgradeneeded=()=>req.result.createObjectStore("pdfs",{keyPath:"id"});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});
const saveRosterPdf=async(meta:SavedRoster,blob:Blob)=>{const db=await rosterDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction("pdfs","readwrite");tx.objectStore("pdfs").put({...meta,blob});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()};
const listRosterPdfs=async()=>{const db=await rosterDb();const data=await new Promise<any[]>((resolve,reject)=>{const r=db.transaction("pdfs").objectStore("pdfs").getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});db.close();return data.sort((a,b)=>b.importedAt.localeCompare(a.importedAt)) as (SavedRoster&{blob:Blob})[]};
const deleteRosterPdf=async(id:string)=>{const db=await rosterDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction("pdfs","readwrite");tx.objectStore("pdfs").delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()};

function RosterLibrary({items,onImport,onDelete}:{items:(SavedRoster&{blob:Blob})[],onImport:()=>void,onDelete:(r:SavedRoster)=>void}){return <section className="roster-library"><div className="roster-title"><div><p className="eyebrow">ARCHIVO PERSONAL</p><h1>Mis rosters</h1><p>Los PDF quedan guardados solamente en este dispositivo.</p></div><button className="import" onClick={onImport}>⇧ Importar PDF</button></div>{items.length?<div className="roster-list">{items.map(r=><div className="roster-item" key={r.id}><button onClick={()=>{const url=URL.createObjectURL(r.blob);window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60000)}}><span className="pdf-icon">PDF</span><div><b>{r.name}</b><small>{new Date(r.from+"T12:00").toLocaleDateString("es-AR",{day:"numeric",month:"short",year:"numeric"})} - {new Date(r.to+"T12:00").toLocaleDateString("es-AR",{day:"numeric",month:"short",year:"numeric"})}</small><small>Importado {new Date(r.importedAt).toLocaleString("es-AR")} · {r.count} jornadas</small></div><span className="open-pdf">Abrir PDF ›</span></button><button className="delete-roster" onClick={()=>onDelete(r)}>Eliminar</button></div>)}</div>:<div className="empty-rosters"><span>▤</span><h2>Todavía no guardaste ningún roster</h2><p>Importá un PDF para conservarlo, verlo y usarlo en el calendario.</p><button onClick={onImport}>Elegir PDF</button></div>}</section>}

function ImportModal({onClose,onImported}:{onClose:()=>void,onImported:(name:string,items:Duty[],blob:Blob)=>void}){
  const [state,setState]=useState<"idle"|"reading"|"done"|"error">("idle"); const [name,setName]=useState("");const [count,setCount]=useState(0);const [error,setError]=useState("");
  const read=async(file?:File)=>{if(!file)return; setName(file.name);setState("reading");try{const buf=await file.arrayBuffer();const head=new TextDecoder("latin1").decode(buf.slice(0,1024));if(!head.includes("%PDF"))throw new Error("El archivo seleccionado no es un PDF válido.");const items=await parseRosterPdfStrict(buf);setCount(items.length);setState("done");onImported(file.name,items,file)}catch(e){setError(e instanceof Error?e.message:"No pudimos leer ese archivo.");setState("error")}};
  return <div className="scrim"><section className="import-card" role="dialog" aria-modal="true"><button className="close" onClick={onClose}>×</button><span className="import-mark">⇧</span><h2>Importar roster</h2><p>Tu PDF se procesa en este dispositivo. No se sube a ningún servidor.</p>
    {state==="idle"&&<label className="drop"><input type="file" accept="application/pdf,.pdf" onChange={e=>read(e.target.files?.[0])}/><strong>Elegir PDF</strong><span>Formato inicial: Crew Daily Roster · ARMS</span></label>}
    {state==="reading"&&<div className="processing"><span/><strong>Analizando {name}</strong><small>Reconociendo jornadas y horarios…</small></div>}
    {state==="done"&&<div className="success"><b>✓</b><strong>Roster reconocido</strong><span>Se cargaron {count} jornadas y abrimos el mes correspondiente.</span><button onClick={onClose}>Ver calendario</button></div>}
    {state==="error"&&<div className="error">{error}<button onClick={()=>setState("idle")}>Intentar de nuevo</button></div>}
    <small className="adapter">ARMS v1 · Lectura local; el PDF no sale de este dispositivo</small>
  </section></div>
}

export default function Home(){
  const [view,setView]=useState<"month"|"agenda"|"rosters">("month"); const [selected,setSelected]=useState<Duty|null>(null); const [showImport,setShowImport]=useState(false); const [showSettings,setShowSettings]=useState(false); const [source,setSource]=useState("Demostración ARMS"); const [filter,setFilter]=useState("all"); const [clock,setClock]=useState<ClockMode>("local"); const [offset,setOffset]=useState(-3);const [allDuties,setAllDuties]=useState<Duty[]>(duties);const [visibleMonth,setVisibleMonth]=useState({y:2025,m:6});const [savedRosters,setSavedRosters]=useState<(SavedRoster&{blob:Blob})[]>([]);const [updateReady,setUpdateReady]=useState(false);
  const {y,m}=visibleMonth; const first=(new Date(y,m,1).getDay()+6)%7; const days=new Date(y,m+1,0).getDate();
  const cellCount=first+days<=35?35:42; const cells=Array.from({length:cellCount},(_,i)=>{const d=i-first+1; if(d<1){const prev=new Date(y,m,d);return {n:prev.getDate(),date:key(prev.getFullYear(),prev.getMonth(),prev.getDate()),muted:true}} if(d>days){return {n:d-days,date:key(y,m+1,d-days),muted:true}} return {n:d,date:key(y,m,d),muted:false}});
  const monthStart=key(y,m,1),monthEnd=key(y,m,days);const shown=(filter==="all"?allDuties:allDuties.filter(d=>d.type===filter)).filter(d=>d.date>=monthStart&&d.date<=monthEnd); const byDate=new Map(shown.map(d=>[d.date,d]));
  const agenda=shown; const today=new Date(),todayKey=key(today.getFullYear(),today.getMonth(),today.getDate());const next=allDuties.find(d=>d.date>=todayKey&&d.type!=="off"&&d.type!=="leave");const period=allDuties.length?`${new Date(allDuties[0].date+"T12:00").toLocaleDateString("es-AR",{day:"numeric",month:"short"})} — ${new Date(allDuties.at(-1)!.date+"T12:00").toLocaleDateString("es-AR",{day:"numeric",month:"short",year:"numeric"})}`:"Sin roster importado";const owner=allDuties.find(d=>d.owner)?.owner;
  const time=(d:Duty,which:"report"|"end"="report")=>clock==="zulu"?(which==="report"?d.reportZ:d.endZ)||"—":shiftZulu(which==="report"?d.reportZ:d.endZ,offset);
  useEffect(()=>{if("serviceWorker" in navigator){navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister())).catch(()=>{})}if("caches" in window){caches.keys().then(keys=>keys.filter(k=>k.startsWith("rumbo-")).forEach(k=>caches.delete(k))).catch(()=>{})}const saved=localStorage.getItem("rumbo-clock");if(saved){try{const p=JSON.parse(saved);setClock(p.clock);setOffset(p.offset)}catch{}}const roster=localStorage.getItem("rumbo-roster-data");if(roster){try{const p=JSON.parse(roster);if(Array.isArray(p.items)&&p.items.length){setSource(p.name||"Roster importado");setAllDuties(p.items);setVisibleMonth(p.month)}}catch{}}listRosterPdfs().then(setSavedRosters).catch(()=>{})},[]);
  const saveSettings=(c:ClockMode,o:number)=>{setClock(c);setOffset(o);localStorage.setItem("rumbo-clock",JSON.stringify({clock:c,offset:o}))};
  const moveMonth=(delta:number)=>{const d=new Date(y,m+delta,1);setVisibleMonth({y:d.getFullYear(),m:d.getMonth()})};
  const imported=async(name:string,items:Duty[],blob:Blob)=>{setSource(name);setAllDuties(items);const counts=new Map<string,number>();items.forEach(d=>{const k=d.date.slice(0,7);counts.set(k,(counts.get(k)||0)+1)});const best=[...counts].sort((a,b)=>b[1]-a[1]||b[0].localeCompare(a[0]))[0][0];const month={y:Number(best.slice(0,4)),m:Number(best.slice(5,7))-1};setVisibleMonth(month);localStorage.setItem("rumbo-roster-data",JSON.stringify({name,items,month}));const meta:SavedRoster={id:`${Date.now()}-${name}`,name,importedAt:new Date().toISOString(),from:items[0].date,to:items.at(-1)!.date,count:items.length};await saveRosterPdf(meta,blob);setSavedRosters(await listRosterPdfs());setFilter("all");setView("month")};
  const removeRoster=async(r:SavedRoster)=>{if(!confirm(`Se eliminarán ${r.name}, el PDF y sus datos solamente de este dispositivo. ¿Continuar?`))return;await deleteRosterPdf(r.id);const remaining=await listRosterPdfs();setSavedRosters(remaining);if(source===r.name){localStorage.removeItem("rumbo-roster-data");setSource("Sin roster importado");setAllDuties([]);const now=new Date();setVisibleMonth({y:now.getFullYear(),m:now.getMonth()})}};
  return <main>
    <header><a className="brand" href="#"><span>R</span><div><b>Rumbo</b><small>MI ROSTER</small></div></a><nav><button className={view==="month"?"active":""} onClick={()=>setView("month")}>Calendario</button><button className={view==="agenda"?"active":""} onClick={()=>setView("agenda")}>Agenda</button><button className={view==="rosters"?"active":""} onClick={()=>setView("rosters")}>Roster</button></nav><button className="settings-button" onClick={()=>setShowSettings(true)} aria-label="Configuración">⚙ <span>{clock==="zulu"?"Zulu":zoneLabel(offset)}</span></button><button className="import" onClick={()=>setShowImport(true)}>⇧ <span>Importar roster</span></button></header>
    {view==="rosters"?<div className="shell"><RosterLibrary items={savedRosters} onImport={()=>setShowImport(true)} onDelete={removeRoster}/></div>:<div className="shell">
      <section className="hero"><div><p className="eyebrow">{period}</p><h1>Hola, {owner||"Leandro"} <span>👋</span></h1><p className="sub">{next?`Próxima actividad: ${new Date(next.date+"T12:00").toLocaleDateString("es-AR",{weekday:"long",day:"numeric",month:"long"})}`:"No hay actividades próximas en este roster."}</p></div><div className="source"><span className="pulse"/><div><b>{source}</b><small>Guardado en este dispositivo</small></div><button aria-label="Opciones">•••</button></div></section>
      {next&&<section className="next-card" onClick={()=>setSelected(next)}><div className="date-box"><small>{weekdays[(new Date(next.date+"T12:00").getDay()+6)%7].toUpperCase()}</small><strong>{Number(next.date.slice(8))}</strong><span>{months[m].slice(0,3).toUpperCase()}</span></div><div className="next-main"><p>ACTIVIDAD DEL MES</p><h2><span className="plane"><DutyIcon type={next.type}/></span> {next.title}</h2><div><span>◷ Presentación <b>{time(next)} {clock==="zulu"?"Z":""}</b></span>{next.reportPlace&&<span>⌖ {next.reportPlace}</span>}<span>{next.note}</span></div></div><button aria-label="Abrir detalle">›</button></section>}
      <div className="toolbar"><div><button aria-label="Mes anterior" onClick={()=>moveMonth(-1)}>‹</button><h2>{months[m][0].toUpperCase()+months[m].slice(1)} {y}</h2><button aria-label="Mes siguiente" onClick={()=>moveMonth(1)}>›</button><button className="today" onClick={()=>{const n=new Date();setVisibleMonth({y:n.getFullYear(),m:n.getMonth()})}}>Hoy</button></div><div className="filters"><button className={filter==="all"?"on":""} onClick={()=>setFilter("all")}>Todos</button><button className={filter==="flight"?"on":""} onClick={()=>setFilter("flight")}>Vuelos</button><button className={filter==="nda"?"on":""} onClick={()=>setFilter("nda")}>NDA</button><button className={filter==="off"?"on":""} onClick={()=>setFilter("off")}>Descanso</button></div></div>
      {view==="month"?<section className="calendar"><div className="weekdays">{weekdays.map(w=><span key={w}>{w}</span>)}</div><div className="grid">{cells.map(c=>{const d=byDate.get(c.date);return <button key={c.date} className={`day ${c.muted?"muted":""} ${d?`has ${d.type}`:""}`} onClick={()=>d&&setSelected(d)}><span className="num">{c.n}</span>{d&&<div className="activity"><span className="activity-icon"><DutyIcon type={d.type}/></span><b>{d.title}</b>{d.type==="flight"&&<small>{time(d)}{clock==="zulu"?" Z":""}{d.reportPlace?` · ${d.reportPlace}`:""}</small>}</div>}</button>})}</div></section>:
      <section className="agenda"><div className="agenda-head"><span>Fecha</span><span>Actividad</span><span>Presentación</span><span>Final</span></div>{agenda.map(d=>{const dt=new Date(d.date+"T12:00");return <button key={d.date} onClick={()=>setSelected(d)}><div className="agenda-date"><strong>{dt.getDate()}</strong><span>{weekdays[(dt.getDay()+6)%7]}</span></div><span className={`agenda-icon ${d.type}`}><DutyIcon type={d.type}/></span><div><b>{d.type==="flight"?(d.legs?.length?d.legs.map(l=>`${l.from}–${l.to}`).join(" · "):d.title):d.title}</b><small>{d.note||`${d.legs?.length||0} tramos${d.total?` · ${d.total}`:""}`}</small></div><time>{time(d)} <small>{clock==="zulu"?"Z":d.reportPlace||""}</small></time><time>{time(d,"end")}</time><i>›</i></button>})}</section>}
      <div className="legend"><span><i className="flight"><DutyIcon type="flight"/></i> Vuelo</span><span><i className="standby"><DutyIcon type="standby"/></i> Guardia / STBY</span><span><i className="nda"><DutyIcon type="nda"/></i> NDA</span><span><i className="off"><DutyIcon type="off"/></i> OFF / R-OFF</span><span><i className="sim"><DutyIcon type="sim"/></i> Simulador</span><span><i className="training">▣</i> Capacitación</span></div>
    </div>}
    {updateReady&&<div className="update-banner"><span>Hay una nueva versión de Rumbo.</span><button onClick={()=>location.reload()}>Actualizar ahora</button></div>}{selected&&<DayDetail duty={selected} onClose={()=>setSelected(null)} offset={offset} clock={clock}/>} {showImport&&<ImportModal onClose={()=>setShowImport(false)} onImported={imported}/>} {showSettings&&<SettingsModal clock={clock} offset={offset} onSave={saveSettings} onClose={()=>setShowSettings(false)}/>} 
  </main>
}

